include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    implementation_imports: false
    avoid_dynamic_calls: false
    avoid_web_libraries_in_flutter: false